In [11]:
%load_ext autoreload
%autoreload 2

In [12]:
import sys
sys.path.append('/Users/tygo/code/perception')

from estimate import estimate_plane
from test import test_plane
from plyfile import PlyData
from RANSAC.algo_utils.ransac import RANSAC
import numpy as np

In [13]:
# reading a ply file and call the estimate_plane function
file_path = "0000000599_0000000846.ply"

ply_data = PlyData.read(file_path)
vertex_data = ply_data["vertex"]

data_dict = {}

# Extract XYZ coordinates
x = np.array(vertex_data["x"])
y = np.array(vertex_data["y"])
z = np.array(vertex_data["z"])
data_dict["points"] = np.column_stack((x, y, z))

result = estimate_plane(data_dict["points"])
print(data_dict['points'])
print(result)

[[1228.3579 3937.3286  114.9498]
 [1233.1185 3936.3813  115.1426]
 [1236.4266 3935.8298  115.0769]
 ...
 [1227.891  3937.2134  115.8192]
 [1227.9049 3937.2104  115.717 ]
 [1234.338  3935.9265  117.7769]]
{'normal': array([-0.18051048,  0.08656913, -0.979756  ], dtype=float32), 'point': array([1186.3873, 3777.9163,  115.451 ], dtype=float32)}


In [14]:
test_result = test_plane(data = data_dict['points'], estimate = result)
test_result

23.701290130615234

In [16]:
import sys
sys.path.append('/Users/tygo/code/perception')
from RANSAC.algo_utils.ransac import RANSAC

ransac_class = RANSAC()
best = ransac_class.RANSAC_fn(data=data_dict['points'], initial_estimate=result, estimate_fn=estimate_plane, test_fn=test_plane)
print(best)
test_plane(data=[data_dict['points']], estimate=best)

0
1
{'normal': array([ 0.05777181, -0.03848352,  0.9975878 ], dtype=float32), 'point': array([1155.5  , 3767.38 ,  114.508], dtype=float32)}


3.2836596965789795

In [ ]:
# ADD MATPLOTLIB STUFF